# Generated by Django 2.0.3 on 2018-07-28 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180727_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=35)),
            ],
        ),
        migrations.AlterField(
            model_name='platter',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platterType', to='orders.PlatterType'),
        ),
    ]
